# fly.toml app configuration file generated for chatgerman on 2023-05-30T19:27:46-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chatgerman"
primary_region = "eze"

[env]
  PORT = "8080"
  OPENAI_API_KEY = "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"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
